spring:
  application:
    name: spring-webapi

  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/tribe
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        boot.allow_jdbc_metadata_access: false
        jdbc.time_zone: UTC
        format_sql: true

  h2:
    console:
      enabled: false

  jackson:
    property-naming-strategy: SNAKE_CASE

logging:
  level:
    org.springframework.security: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,env
  endpoint:
    env:
      show-values: never  # Redact secrets even when env is exposed


app:
  security:
    jwt:
      secret: ${JWT_SECRET:?JWT_SECRET environment variable must be provided}
      access-token-ttl-seconds: 900
      refresh-token-ttl-seconds: 604800

