spring:
  datasource:
    url: ${DATABASE_URL:jdbc:h2:mem:tribe;DB_CLOSE_DELAY=-1;MODE=PostgreSQL}
    username: ${DATABASE_USERNAME:sa}
    password: ${DATABASE_PASSWORD:}
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: false
  jackson:
    property-naming-strategy: SNAKE_CASE

logging:
  level:
    org.springframework.security: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info

app:
  security:
    jwt:
      secret: ${JWT_SECRET:?JWT_SECRET environment variable must be provided}
      access-token-ttl-seconds: 900
      refresh-token-ttl-seconds: 604800
