name: CI/CD - Build and Push to ECR

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  ECR_REPOSITORY: devashish/tribe-backend
  IMAGE_TAG: ${{ github.sha }}
  WORKING_DIRECTORY: spring-webapi

jobs:
  build-test-and-push:
    name: Build, Test, and Push Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven
          cache-dependency-path: ${{ env.WORKING_DIRECTORY }}/pom.xml

      - name: Run test suite
        run: mvn -B test
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Run build mock production package
        run: mvn -B -DskipTests package
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push image (commit tag)
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.WORKING_DIRECTORY }}
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

      - name: Tag image as latest
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag \
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} \
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest

      - name: Use repo task definition template
        run: cp .github/ecs/task-definition.json task-def.json

      - name: Update task definition with image and commit SHA
        run: |
          NEW_IMAGE="${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}"
          COMMIT_SHA="${{ github.sha }}"
          cat task-def.json | \
            jq --arg IMG "$NEW_IMAGE" --arg SHA "$COMMIT_SHA" \
            '.containerDefinitions[0].image = $IMG | .tags[0].value = $SHA' \
            > task-def-final.json

      - name: Register new task definition revision
        id: register-task-def
        run: |
          DB_USER="${{ secrets.DB_USER }}"
          DB_PASS="${{ secrets.DB_PASS }}"
          jq \
            --arg USER_ARN "$DB_USER" \
            --arg PASS_ARN "$DB_PASS" \
            '.containerDefinitions[0].environment = [
              { "name": "DB_USERNAME", "from": $USER_ARN },
              { "name": "DB_PASSWORD", "from": $PASS_ARN }
            ]' \
            task-def.json > task-def-final.json

          TASK_DEF_ARN=$(aws ecs register-task-definition \
            --cli-input-json file://task-def-final.json \
            --query taskDefinition.taskDefinitionArn \
            --output text)
          echo "TASK_DEF_ARN=$TASK_DEF_ARN" >> $GITHUB_ENV

      - name: Deploy to ECS
        run: |
          aws ecs update-service \
            --cluster ${{ secrets.ECS_CLUSTER }} \
            --service ${{ secrets.ECS_SERVICE }} \
            --task-definition ${{ env.TASK_DEF_ARN }}
